# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "LINEHOUSE"
description: > # this means to ignore newlines until "email:"
   architectural design

email: info@linehousedesign.com
#blog logo
logo: "/assets/images/main-site-images/linehouse-icon.png"
# blog cover
cover: "/assets/images/projects/dressed-ifc/dressed-sh-001.jpg"

name: 'Linehouse Shanghai Limited 联图'
author: 'Linehouse'
author_image: "/assets/images/main-site-images/author.jpg"

paginate:	10

url: "http://linehousedesign.com" # the base hostname & protocol for the site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/linehousedesign
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/linehousedesign
    desc: Connect with us on facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	google-plus
    url:	https://google.com/+linehousedesign
    desc:	Add us on google+
    share_url:
    share_title:
    share_link:
